package system.entity;

import java.io.Serializable;
import java.util.Date;

public class SysDict implements Serializable {
    /**
     * 编号
     */
    private String id;

    /**
     * 代码
     */
    private String itemCode;

    /**
     * 名称
     */
    private String itemName;

    /**
     * 类型(分类/项目)
     */
    private String typeCode;

    /**
     * 描述
     */
    private String typeName;

    /**
     * 排序（升序）
     */
    private Long sort;

    /**
     * 创建者
     */
    private String createBy;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 更新者
     */
    private String updateBy;

    /**
     * 更新时间
     */
    private Date updateDate;

    /**
     * 备注信息
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.id
     *
     * @return the value of sys_dict.id
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.id
     *
     * @param id the value for sys_dict.id
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.item_code
     *
     * @return the value of sys_dict.item_code
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.item_code
     *
     * @param itemCode the value for sys_dict.item_code
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.item_name
     *
     * @return the value of sys_dict.item_name
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.item_name
     *
     * @param itemName the value for sys_dict.item_name
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.type_code
     *
     * @return the value of sys_dict.type_code
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.type_code
     *
     * @param typeCode the value for sys_dict.type_code
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.type_name
     *
     * @return the value of sys_dict.type_name
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.type_name
     *
     * @param typeName the value for sys_dict.type_name
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.sort
     *
     * @return the value of sys_dict.sort
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.sort
     *
     * @param sort the value for sys_dict.sort
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.create_by
     *
     * @return the value of sys_dict.create_by
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.create_by
     *
     * @param createBy the value for sys_dict.create_by
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.create_date
     *
     * @return the value of sys_dict.create_date
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.create_date
     *
     * @param createDate the value for sys_dict.create_date
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.update_by
     *
     * @return the value of sys_dict.update_by
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.update_by
     *
     * @param updateBy the value for sys_dict.update_by
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.update_date
     *
     * @return the value of sys_dict.update_date
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.update_date
     *
     * @param updateDate the value for sys_dict.update_date
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.remarks
     *
     * @return the value of sys_dict.remarks
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.remarks
     *
     * @param remarks the value for sys_dict.remarks
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}