package system.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @author MBG
 */
public class SysDept implements Serializable {
    /**
     * 编号
     */
    private String id;

    /**
     * 父级编号
     */
    private String parentId;

    /**
     * 所有父级编号（建议不使用）
     */
    private String parentIds;

    /**
     * 名称
     */
    private String name;

    /**
     * 排序
     */
    private Long sort;

    /**
     * 创建者
     */
    private String createBy;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 更新者
     */
    private String updateBy;

    /**
     * 更新时间
     */
    private Date updateDate;

    /**
     * 备注信息
     */
    private String remarks;

    /**
     * 注册资本
     */
    private String registeredCapital;

    /**
     * 联系电话
     */
    private String phoneNumber;

    /**
     * 唯一社会信用代码
     */
    private String creditCode;

    /**
     * 公司地址
     */
    private String address;

    /**
     * 身份证号码
     */
    private String idcardNumber;

    /**
     * 开户行
     */
    private String bank;

    /**
     * 银行支行
     */
    private String bankBranch;

    /**
     * 户名
     */
    private String accountName;

    /**
     * 账号
     */
    private String accountNumber;

    /**
     * 区分钢厂(0)、一级供货商(1)、二级供货商(2)
     */
    private String type;

    /**
     * 是否认证（1是，0否）
     */
    private String isAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.id
     *
     * @return the value of sys_dept.id
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.id
     *
     * @param id the value for sys_dept.id
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.parent_id
     *
     * @return the value of sys_dept.parent_id
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.parent_id
     *
     * @param parentId the value for sys_dept.parent_id
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.parent_ids
     *
     * @return the value of sys_dept.parent_ids
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.parent_ids
     *
     * @param parentIds the value for sys_dept.parent_ids
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.name
     *
     * @return the value of sys_dept.name
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.name
     *
     * @param name the value for sys_dept.name
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.sort
     *
     * @return the value of sys_dept.sort
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.sort
     *
     * @param sort the value for sys_dept.sort
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.create_by
     *
     * @return the value of sys_dept.create_by
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.create_by
     *
     * @param createBy the value for sys_dept.create_by
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.create_date
     *
     * @return the value of sys_dept.create_date
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.create_date
     *
     * @param createDate the value for sys_dept.create_date
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.update_by
     *
     * @return the value of sys_dept.update_by
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.update_by
     *
     * @param updateBy the value for sys_dept.update_by
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.update_date
     *
     * @return the value of sys_dept.update_date
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.update_date
     *
     * @param updateDate the value for sys_dept.update_date
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.remarks
     *
     * @return the value of sys_dept.remarks
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.remarks
     *
     * @param remarks the value for sys_dept.remarks
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.registered_capital
     *
     * @return the value of sys_dept.registered_capital
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.registered_capital
     *
     * @param registeredCapital the value for sys_dept.registered_capital
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital == null ? null : registeredCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.phone_number
     *
     * @return the value of sys_dept.phone_number
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.phone_number
     *
     * @param phoneNumber the value for sys_dept.phone_number
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.credit_code
     *
     * @return the value of sys_dept.credit_code
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.credit_code
     *
     * @param creditCode the value for sys_dept.credit_code
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.address
     *
     * @return the value of sys_dept.address
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.address
     *
     * @param address the value for sys_dept.address
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.idcard_number
     *
     * @return the value of sys_dept.idcard_number
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.idcard_number
     *
     * @param idcardNumber the value for sys_dept.idcard_number
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber == null ? null : idcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.bank
     *
     * @return the value of sys_dept.bank
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.bank
     *
     * @param bank the value for sys_dept.bank
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.bank_branch
     *
     * @return the value of sys_dept.bank_branch
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.bank_branch
     *
     * @param bankBranch the value for sys_dept.bank_branch
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch == null ? null : bankBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.account_name
     *
     * @return the value of sys_dept.account_name
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.account_name
     *
     * @param accountName the value for sys_dept.account_name
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.account_number
     *
     * @return the value of sys_dept.account_number
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.account_number
     *
     * @param accountNumber the value for sys_dept.account_number
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber == null ? null : accountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.type
     *
     * @return the value of sys_dept.type
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.type
     *
     * @param type the value for sys_dept.type
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.is_auth
     *
     * @return the value of sys_dept.is_auth
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public String getIsAuth() {
        return isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.is_auth
     *
     * @param isAuth the value for sys_dept.is_auth
     *
     * @mbg.generated Wed Dec 26 20:21:08 CST 2018
     */
    public void setIsAuth(String isAuth) {
        this.isAuth = isAuth == null ? null : isAuth.trim();
    }
}