package system.entity;

import java.io.Serializable;

public class SysRoleDept implements Serializable {
    /**
     * 角色编号
     */
    private String roleId;

    /**
     * 机构编号
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_dept
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_dept.role_id
     *
     * @return the value of sys_role_dept.role_id
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_dept.role_id
     *
     * @param roleId the value for sys_role_dept.role_id
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_dept.dept_id
     *
     * @return the value of sys_role_dept.dept_id
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_dept.dept_id
     *
     * @param deptId the value for sys_role_dept.dept_id
     *
     * @mbggenerated Thu Oct 25 14:52:49 CST 2018
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }
}