spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    view:
      suffix: .html
      prefix: /templates/
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useInformationSchema=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
#redis配置
  redis:
      #  数据库索引
    database: 1
      #    服务器地址
    host: 114.115.158.120
      #    服务器连接端口
    port: 6379
      #    链接密码
    password: 7326itcx
      #时间+8小时
    jackson:
      time-zone: GMT+8    #或UTC
#mybatis-plus
mybatis-plus:
  configuration:
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    id-type: 0
  mapper-locations:
    - classpath*:/mapper/**/*.xml


